import type { Metadata } from "next";
import { ReactNode } from "react";

import "./globals.css";
import { ApiClientProvider } from "@/contexts/ApiContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Providers = ({ children }: { children: ReactNode }) => {
  return <ApiClientProvider>
    {children}
  </ApiClientProvider>;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
