import type { Metadata } from "next";
import { ReactNode } from "react";
import { Raleway } from "next/font/google";

import "./globals.css";
import { ApiClientProvider } from "@/contexts/ApiContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "@/components/ui/atoms/sonner";
import { AccountsProvider } from "@/contexts/AccountsContext";
import { NavigationProvider } from "@/contexts/NavigationContext";
import { NavigationLoader } from "@/components/providers/NavigationLoader";
import { BeneficiariesProvider } from "@/contexts/BeneficiariesContext";
import { SettingsProvider } from "@/contexts/SettingsContext";
import { UsersProvider } from "@/contexts/UsersContext";
import { SseApiClientProvider } from "@/contexts/SseApiContext";
import { OperationsProvider } from "@/contexts/OperationsContext";
import { BankCreditsProvider } from "@/contexts/BankCreditContext";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Providers = ({ children }: { children: ReactNode }) => {
  return (
    <NavigationProvider>
      <ApiClientProvider>
        <AuthProvider>
          <SseApiClientProvider>
            <AccountsProvider>
              <OperationsProvider>
                <BeneficiariesProvider>
                  <SettingsProvider>
                    <UsersProvider>
                      <BankCreditsProvider>{children}</BankCreditsProvider>
                    </UsersProvider>
                  </SettingsProvider>
                </BeneficiariesProvider>
              </OperationsProvider>
            </AccountsProvider>
          </SseApiClientProvider>
        </AuthProvider>
      </ApiClientProvider>
    </NavigationProvider>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={raleway.variable} suppressHydrationWarning={true}>
        <Providers>
          <NavigationLoader>{children}</NavigationLoader>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
